### ISSUE TITLE
后续更新咨询

### ISSUE THREAD

**Issue by z666pr** [NTDXYG/ComFormer#1]
感谢您的分享，请问后续是否会更新论文中提到的源码和数据集部分？如有更新，不胜感激

再次感谢您的分享~

**Comment by NTDXYG** [comment]
会的，在整理了，会议汇报完就放出来

**Comment by NTDXYG** [comment]
代码整理完了，数据集和生成的注释很不幸今天早上被我学妹删了。。数据集可以在https://github.com/xing-hu/EMSE-DeepCom 下载，code转sim_sbt的方法在utils代码里了。还要注意的就是数据集预处理，我限制代码和抽象语法树序列的长度在256，多的部分截断了，然后拼接的。这点在论文里可能没提及太详细。有问题的话继续留言我会处理的。

**Comment by z666pr** [comment]
> 代码整理完了，数据集和生成的注释很不幸今天早上被我学妹删了。。数据集可以在https://github.com/xing-hu/EMSE-DeepCom 下载，code转sim_sbt的方法在utils代码里了。还要注意的就是数据集预处理，我限制代码和抽象语法树序列的长度在256，多的部分截断了，然后拼接的。这点在论文里可能没提及太详细。有问题的话继续留言我会处理的。

感谢分享！ 请问能否生成一个requirements.txt？对这些库的版本不太清楚！非常感谢！

**Comment by NTDXYG** [comment]
我更新了下readme：
This repo uses [javalang](https://github.com/c2nes/javalang), [transformers](https://github.com/huggingface/transformers), [simpletransformers](https://github.com/ThilinaRajapakse/simpletransformers), [pytorch](https://pytorch.org/), and [nlgeval](https://github.com/Maluuba/nlg-eval).
安装最新版本就能运行了
